# Generated by Django 5.0.6 on 2024-05-16 11:45

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('job', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('service', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('icon', models.CharField(choices=[('lni-cog', 'Gear'), ('lni-stats-up', 'Graphic'), ('lni-users', 'Users'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rock')], max_length=20, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('bio', models.TextField(max_length=200, verbose_name='Bio')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='team', variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Image')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
