# Generated by Django 5.0.6 on 2024-05-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('icon', models.CharField(choices=[('lni-rocket', 'Rocket'), ('lni-laptop-phone', 'Laptop-phone'), ('lni-cog', 'Gear'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Layers'), ('lni-leaf', 'Leaf')], max_length=20, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
