# Generated by Django 5.0.6 on 2024-05-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(choices=[('lni-rocket', 'Rocket'), ('lni-laptop-phone', 'Laptop-phone'), ('lni-cog', 'Gear'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Layers')], max_length=20, verbose_name='icon'),
        ),
    ]
